### ISSUE TITLE
 Chocolate chunks are better than chocolate chips

### ISSUE THREAD

**Issue by m0namon** [m0namon/cookies#6]
Issue replicated from upstream bcyphers/cookies#1.

> In every way. Chips are just miniature hershey's kisses, the most disappointing of chocolate candies. Chunks are big, bold, evocative. Why would you want cookies with wimpy little "chips" of chocolate when you can have thick, melty chunks?

> Replace all references to "chip" with "chunk" to make the recipe more clear.

**Comment by roujiawen** [comment]
Working on it!
